import { Division, Category, FaqItem } from './types';

export const divisions: Division[] = [
  {
    id: 'comercio',
    name: 'Comércio',
    icon: 'ShoppingCart',
    color: 'border-blue-500',
  },
  {
    id: 'logistica',
    name: 'Logística',
    icon: 'Truck',
    color: 'border-green-500',
  },
  {
    id: 'passageiros',
    name: 'Passageiros',
    icon: 'Bus',
    color: 'border-orange-500',
  },
  {
    id: 'geral',
    name: 'Geral (Field Service)',
    icon: 'Settings',
    color: 'border-purple-500',
  },
];

export const categories: Category[] = [
  { id: 'sistemas', name: 'Sistemas', divisionId: 'comercio', icon: 'Monitor' },
  { id: 'acessos', name: 'Acessos', divisionId: 'comercio', icon: 'Key' },
  { id: 'hardware', name: 'Hardware', divisionId: 'comercio', icon: 'Laptop' },
  { id: 'rede', name: 'Rede', divisionId: 'comercio', icon: 'Wifi' },

  { id: 'sistemas-log', name: 'Sistemas', divisionId: 'logistica', icon: 'Monitor' },
  { id: 'rastreamento', name: 'Rastreamento', divisionId: 'logistica', icon: 'Navigation' },
  { id: 'equipamentos', name: 'Equipamentos', divisionId: 'logistica', icon: 'Package' },
  { id: 'comunicacao', name: 'Comunicação', divisionId: 'logistica', icon: 'Radio' },

  { id: 'sistemas-pass', name: 'Sistemas', divisionId: 'passageiros', icon: 'Monitor' },
  { id: 'bilhetagem', name: 'Bilhetagem', divisionId: 'passageiros', icon: 'CreditCard' },
  { id: 'cameras', name: 'Câmeras', divisionId: 'passageiros', icon: 'Camera' },
  { id: 'wi-fi', name: 'Wi-Fi', divisionId: 'passageiros', icon: 'Wifi' },

  { id: 'geral-sistemas', name: 'Sistemas', divisionId: 'geral', icon: 'Monitor' },
  { id: 'infraestrutura', name: 'Infraestrutura', divisionId: 'geral', icon: 'Server' },
  { id: 'suporte', name: 'Suporte Geral', divisionId: 'geral', icon: 'HeadphonesIcon' },
  { id: 'telefonia', name: 'Telefonia', divisionId: 'geral', icon: 'Phone' },
  { id: 'computador', name: 'Computador', divisionId: 'geral', icon: 'Monitor' },
  { id: 'impressora', name: 'Impressora', divisionId: 'geral', icon: 'Printer' },
  { id: 'email', name: 'Email', divisionId: 'geral', icon: 'Mail' },
];

export const faqItems: FaqItem[] = [
  {
    id: '1',
    question: 'Como solicitar acesso a um novo sistema?',
    answer: 'Para solicitar acesso a um novo sistema, você deve abrir um chamado através do Field Service informando: nome completo, matrícula, departamento e o sistema desejado. O prazo médio de liberação é de até 2 dias úteis após aprovação do gestor.',
    categoryId: 'acessos',
    tip: 'Dica: Tenha em mãos a justificativa de uso do sistema para agilizar a aprovação.',
  },
  {
    id: '2',
    question: 'Esqueci minha senha, como recuperar?',
    answer: 'Para recuperar sua senha, acesse o portal de autoatendimento em https://senha.gab.com.br e clique em "Esqueci minha senha". Será enviado um link de recuperação para seu e-mail corporativo. Caso não tenha acesso ao e-mail, entre em contato com o suporte através do ramal 3000.',
    categoryId: 'acessos',
    tip: 'Dica: Se o link não funcionar, verifique se o e-mail está correto e se o domínio gab.com.br está liberado no firewall.',
  },
  {
    id: '3',
    question: 'Meu computador está lento, o que fazer?',
    answer: 'Primeiro, verifique se existem muitos programas abertos simultaneamente. Feche aplicações desnecessárias e reinicie o computador. Se o problema persistir, abra um chamado no Field Service detalhando os sintomas e quando o problema começou.',
    categoryId: 'hardware',
    tip: 'Dica: Evite manter muitos programas abertos ao mesmo tempo para manter o desempenho do computador.',
  },
  {
    id: '4',
    question: 'Como configurar impressora de rede?',
    answer: 'Acesse Painel de Controle > Dispositivos e Impressoras > Adicionar Impressora. Selecione a impressora de rede desejada. Se não aparecer na lista, solicite suporte através do Field Service informando sua localização e a impressora que deseja configurar.',
    categoryId: 'hardware',
    tip: 'Dica: Certifique-se de que o computador esteja na mesma rede da impressora.',
  },
  {
    id: '5',
    question: 'Não consigo acessar a internet, como proceder?',
    answer: 'Verifique se o cabo de rede está conectado corretamente. Teste outros sites para confirmar se é problema geral ou específico. Reinicie seu computador. Se o problema persistir, abra um chamado informando sua localização e número do patrimônio do equipamento.',
    categoryId: 'rede',
    tip: 'Dica: Verifique se o cabo de rede está conectado corretamente e se o computador está na mesma sub-rede do roteador.',
  },
  {
    id: '6',
    question: 'Como solicitar instalação de software?',
    answer: 'Abra um chamado no Field Service especificando o software necessário, a versão (se aplicável) e a justificativa de uso. A solicitação passará por análise de segurança e aprovação do gestor antes da instalação.',
    categoryId: 'sistemas',
    tip: 'Dica: Forneça o máximo de detalhes sobre o software para agilizar a análise e aprovação.',
  },
  {
    id: '7',
    question: 'O sistema de rastreamento não está atualizando, o que fazer?',
    answer: 'Verifique se há conexão com a internet e se o GPS do veículo está ligado. Aguarde 5 minutos e atualize a página. Se o problema persistir, anote o número do veículo e horário da última atualização e abra um chamado no Field Service.',
    categoryId: 'rastreamento',
    tip: 'Dica: Verifique se o veículo está em uma área com boa cobertura de sinal para garantir a atualização do rastreamento.',
  },
  {
    id: '8',
    question: 'Como configurar rádio comunicador?',
    answer: 'Os rádios comunicadores são pré-configurados pela equipe técnica. Caso precise de ajustes nos canais ou tenha problemas de comunicação, abra um chamado informando o número do equipamento e sua base operacional.',
    categoryId: 'comunicacao',
    tip: 'Dica: Verifique se o rádio está dentro da cobertura da base operacional e se o canal está correto.',
  },
  {
    id: '9',
    question: 'Validador de bilhetagem apresentando erro, como resolver?',
    answer: 'Reinicie o equipamento segurando o botão power por 10 segundos. Aguarde a reinicialização completa (aprox. 2 minutos). Se o erro persistir, anote o código do erro exibido na tela e abra um chamado urgente informando o número do veículo.',
    categoryId: 'bilhetagem',
    tip: 'Dica: Se o problema persistir após reiniciar, verifique se o equipamento está conectado corretamente à rede elétrica.',
  },
  {
    id: '10',
    question: 'Câmera do ônibus não está gravando, o que fazer?',
    answer: 'Verifique se o DVR está ligado (luz verde acesa). Confirme se há espaço no HD (verificar no monitor). Em caso de falha, anote o número do veículo e a câmera com problema (frontal, traseira, interna) e abra um chamado prioritário.',
    categoryId: 'cameras',
    tip: 'Dica: Se o DVR estiver desligado, verifique o fusível correspondente no painel de fusíveis do veículo.',
  },
  {
    id: '11',
    question: 'Passageiros reclamando de Wi-Fi instável, como proceder?',
    answer: 'Verifique se o roteador está ligado e com todas as luzes normais. Teste a conexão com seu celular. Se confirmado o problema, anote o número do veículo e horário e abra um chamado para análise técnica.',
    categoryId: 'wi-fi',
    tip: 'Dica: Verifique se o roteador está dentro da cobertura do Wi-Fi e se há outros dispositivos conectados.',
  },
  {
    id: '12',
    question: 'Como abrir um chamado no Field Service?',
    answer: 'Acesse o portal Field Service através do link no portal do colaborador ou clique no botão "Abrir Chamado" neste FAQ. Preencha todos os campos obrigatórios: tipo de problema, descrição detalhada, localização e nível de urgência. Você receberá um número de protocolo por e-mail.',
    categoryId: 'suporte',
    tip: 'Dica: Forneça o máximo de detalhes possível para agilizar a resolução do seu chamado.',
  },
  {
    id: '13',
    question: 'Qual o prazo médio de atendimento?',
    answer: 'Os prazos variam conforme a prioridade: Urgente (problemas críticos que impedem operação) - até 4 horas; Alta (impacta múltiplos usuários) - até 8 horas; Normal (problemas individuais) - até 24 horas; Baixa (melhorias e dúvidas) - até 48 horas.',
    categoryId: 'suporte',
    tip: 'Dica: Em caso de urgência, entre em contato diretamente com o suporte técnico pelo ramal 4000.',
  },
  {
    id: '14',
    question: 'Telefone corporativo sem sinal, como resolver?',
    answer: 'Verifique se o aparelho está carregado e se o modo avião está desligado. Tente reiniciar o aparelho. Se o problema persistir, anote o número da linha e abra um chamado com o Field Service para análise da operadora.',
    categoryId: 'telefonia',
    tip: 'Dica: Se o problema persistir após reiniciar, verifique se o aparelho está dentro da cobertura da operadora.',
  },
  {
    id: '15',
    question: 'Servidor fora do ar, qual o procedimento?',
    answer: 'Entre em contato IMEDIATAMENTE com o NOC (Network Operations Center) pelo ramal 4000 ou WhatsApp (27) 99999-0000. Informe qual servidor/sistema está indisponível e o impacto na operação. Chamados críticos de infraestrutura têm prioridade máxima.',
    categoryId: 'infraestrutura',
    tip: 'Dica: Em caso de falha crítica, não espere a aprovação do chamado. Contate o NOC diretamente para aceleração do processo.',
  },
  {
    id: '16',
    question: 'Minha senha do Windows expirou, o que fazer?',
    answer: 'Se você estiver na rede da empresa, pressione Ctrl + Alt + Del e selecione "Alterar uma senha". Caso esteja remoto, conecte a VPN antes.',
    categoryId: 'computador',
    tip: 'Caminho no portal: Computador > Acessos > Alteerar senha',
  },
  {
    id: '17',
    question: 'Como solicitar um novo computador?',
    answer: 'Abra um chamado no Field Service informando o motivo da solicitação, o modelo desejado (se aplicável) e a urgência. A equipe de TI avaliará a necessidade e entrará em contato para aprovação e agendamento da entrega.',
    categoryId: 'computador',
    tip: 'Dica: Forneça detalhes sobre o uso pretendido do computador para ajudar na avaliação da solicitação.',
  },{
    id: '18',
    question: 'Recebi uma máquina nova e não sei o que fazer',
    answer: 'Antes de trazer para o laboratório, certifique-se de que a etiqueta de patrimônio já está colada no equipamento, o pacote Office já foi providenciado e que o usuário que irá usar a máquina já possui uma conta criada.',
    categoryId: 'computador',
    tip: 'Caminho no portal: Suporte > Novas Máquinas > Checklist de Configuração',
  },
  {
    id: '19',
    question: 'Não estou conseguindo imprimir',
    answer: 'Verifique se tanto a impressora quanto o seu computador estão ligados e conectados à rede. Em seguida abra um chamado e nos encaminhe o modelo da impressora e o endereço de IP dela ',
    categoryId: 'impressora',
    tip: 'Caminho no portal: Suporte > Impressoras > Instalarção e Configuração',
  },
  {
    id: '20',
    question: 'Preciso formatar minha máquina, como faço?',
    answer: 'Abra um chamado informando o motivo da formatação e quais dias e horários você tem disponibilidade para levar a máquina até o laboratório. Entraremos em contato para realizar o agendamento.',
    categoryId: 'computador',
    tip: 'Caminho no portal: Windows > Formatar',
  },
  {
    id: '21',
    question: 'Preciso configurar/reconfigurar meu e-mail no aplicativo do celular',
    answer: 'Primeiro, certifique-se de que tem em seu celular instalado os aplicativos "Microsoft Authenticator", "Outlook" e VPN Capsule. Em seguida, traga seu celular para o laboratório para que possamos realizar a configuração presencialmente.',
    categoryId: 'email',
    tip: 'Caminho no portal: Outlook > Configurar',
  },
  {
    id: '22',
    question: 'Solicitar a troca de alguma peça do meu computador (teclado, tela, bateria, conector de fonte etc)',
    answer: 'Abra um chamado informando qual peça precisa ser trocada e o motivo. Em seguida, encaminhe a máquina para o laboratório para que possamos avaliar e providenciar o laudo, caso necessário.',
    categoryId: 'computador',
    tip: 'Caminho no portal: Hardware > Troca de Peça > Solicitação de laudo técnico',
  },
  {
    id: '23',
    question: 'Solicitar a instalação da peça nova que foi comprada',
    answer: 'Abra um chamado informando que a peça foi comprada e solicitando a instalação. Em seguida, nos informe qual o melhor horário para levar a máquina até o laboratório para que possamos realizar a instalação presencialmente.',
    categoryId: 'computador',
    tip: 'Caminho no portal: Hardware > Instalação de Peça Nova',
  },
  {
    id: '24',
    question: 'Quero um ramal do next ip em minha máquina',
    answer: 'Abra um chamado informando o número do ramal desejado e o motivo da solicitação. A equipe de TI verificará a disponibilidade e entrará em contato para aprovação e configuração.',
    categoryId: 'telefonia',
    tip: 'Caminho no portal: Sistemas > Ramal Next IP',
  }
];
